FROM mcr.microsoft.com/dotnet/sdk:7.0 as build

WORKDIR /app

COPY FluentApi.sln /app/

COPY AvailabilityApiService .
COPY BusinessLogic .
COPY FluentApi .
COPY Models .

# RUN dotnet run --project AvailabilityApiService

RUN dotnet publish FluentApi.sln

# FROM mcr.microsoft.com/dotnet/aspnet:7.0 as run

# WORKDIR /app

# COPY --from=build /app/publish .